<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Platforms>AnyCPU;x86</Platforms>
    <RootNamespace>gTranslateMicrosoftTranslatorPlugin</RootNamespace>
    <AssemblyName>gTranslateMicrosoftTranslatorPlugin.scplug</AssemblyName>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <PlatformTarget Condition="'$(Platform)' == 'x86'">x86</PlatformTarget>
    <Configurations>Debug;Release;release-small</Configurations>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <OutputPath>..\sayclip\plugins\gTranslateMicrosoftTranslator\</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <OutputPath>..\sayclip\plugins\gTranslateMicrosoftTranslator\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="GTranslate" Version="2.2.8" />
    <PackageReference Include="System.ComponentModel.Composition" Version="9.0.0" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\sayclip.contracts\sayclip.contracts.csproj">
      <Private>false</Private>
      <ExcludeAssets>runtime</ExcludeAssets>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>
