<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Platforms>AnyCPU;x86</Platforms>
    <RootNamespace>consoleTranslatorTest</RootNamespace>
    <AssemblyName>consoleTranslatorTest</AssemblyName>
    <PlatformTarget Condition="'$(Platform)' == 'x86'">x86</PlatformTarget>
    <Configurations>Debug;Release;release-full;release-small</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NLog" Version="5.3.4" />
    <PackageReference Include="System.ServiceModel.Http" Version="8.0.0" />
    <PackageReference Include="System.ServiceModel.Primitives" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\logSystem\logSystem.csproj" />
    <ProjectReference Include="..\sayclip\sayclip.csproj" />
  </ItemGroup>

  <!-- WCF Service References -->

  <ItemGroup>
    <None Include="app.config" />
  </ItemGroup>

  <Target Name="PostBuildActions" AfterTargets="Build">
    <Exec Command="xcopy /s /e /y &quot;$(ProjectDir)..\sayclip\plugins&quot; &quot;$(ProjectDir)$(OutDir)plugins&quot;" Condition="'$(OS)' == 'Windows_NT'" />
    <Exec Command="ROBOCOPY &quot;$(TargetDir) &quot; &quot;$(TargetDir)lib\ &quot; *.dll *.xml *.pdb /XF $(TargetFileName) jfwapi.dll nvdaControllerClient.dll SAAPI32.dll ScreenReaderAPI.dll UniversalSpeech.dll *.exe *.config *.manifest /XD lib * /E /IS /MOV&#xA;if %25errorlevel%25 leq 4 exit 0 else exit %25errorlevel%25" Condition="'$(OS)' == 'Windows_NT'" />
  </Target>

</Project>