<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <RootNamespace>logSystem</RootNamespace>
    <AssemblyName>logSystem</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NLog" Version="5.3.4" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="NLog.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>