<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Platforms>AnyCPU;x86</Platforms>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>sayclipTray</RootNamespace>
    <AssemblyName>sayclip</AssemblyName>
    <StartupObject>sayclipTray.Program</StartupObject>
    <PlatformTarget Condition="'$(Platform)' == 'x86'">x86</PlatformTarget>
    <SelfContained Condition="'$(Configuration)' == 'Release'">true</SelfContained>
    <SelfContained Condition="'$(Configuration)'=='release-full'">true</SelfContained>
    <RuntimeIdentifier Condition="'$(Configuration)' == 'Release'">win-x86</RuntimeIdentifier>
    <RuntimeIdentifier Condition="'$(Configuration)'=='release-full'">win-x86</RuntimeIdentifier>
    <Configurations>Debug;Release;release-full;release-small</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <ApplicationDefinition Remove="App.xaml" />
    <Page Include="App.xaml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Autoupdater.NET.Official" Version="1.9.2" />
    <PackageReference Include="Hardcodet.NotifyIcon.Wpf" Version="2.0.1" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.2957.106" />
    <PackageReference Include="MouseKeyHook" Version="5.7.1" />
    <PackageReference Include="NLog" Version="5.3.4" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AssemblySettings\AssemblySettings.csproj" />
    <ProjectReference Include="..\logSystem\logSystem.csproj" />
    <ProjectReference Include="..\sayclip\sayclip.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Red.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <Target Name="PostBuildActions" AfterTargets="Build">
    <Exec Command="xcopy /s /e /y &quot;$(ProjectDir)..\sayclip\plugins&quot; &quot;$(ProjectDir)$(OutDir)plugins&quot;" Condition="'$(OS)' == 'Windows_NT'" />
    <Exec Command="ROBOCOPY &quot;$(TargetDir) &quot; &quot;$(TargetDir)lib\ &quot; *.dll *.xml *.pdb /XF $(TargetFileName) jfwapi.dll nvdaControllerClient.dll SAAPI32.dll ScreenReaderAPI.dll UniversalSpeech.dll *.exe *.config *.manifest /XD lib * /E /IS /MOV&#xA;if %25errorlevel%25 leq 4 exit 0 else exit %25errorlevel%25" Condition="'$(OS)' == 'Windows_NT'" />
  </Target>

</Project>