name: build and release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: build sayclip
    runs-on: windows-latest
    steps:
      - name: setup_devenv
        uses: microsoft/setup-msbuild@v1
      - name: cache sayclip
        id: cache-build
        uses: actions/cache@v2
        with:
          path: |
            sayclip.zip
            sayclip/version.xml
          key: sayclip-build
          restore-keys: |
            sayclip-build
            sayclip
      - name: checkout
        uses: actions/checkout@v2
      - name: build sayclip
        run: |
          cd sayclip
          nuget restore sayclip.sln
          cd googleTranslatorPlugin
          msbuild . -p:configuration=release
          cd ..\sayclipTray
          msbuild . -p:configuration=release
          cd ..\..
          tar -a -c -f sayclip.zip sayclip\sayclipTray\bin\release
  release:
    name: release sayclip
    needs: build
    runs-on: ubuntu-latest
    steps: 
      - name: get cache
        uses: actions/cache@v2
        with:
          path: |
            sayclip.zip
            sayclip/version.xml
          key: sayclip-build
          restore-keys: |
            sayclip-build
            sayclip
      - name: release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "sayclip.zip,sayclip/version.xml"
          artifactErrorsFailBuild: true
          token: ${{ secrets.GITHUB_TOKEN }}